//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace SGRIMvc.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class StringConexaoSGRI_BD : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new StringConexaoSGRI_BD object using the connection string found in the 'StringConexaoSGRI_BD' section of the application configuration file.
        /// </summary>
        public StringConexaoSGRI_BD() : base("name=StringConexaoSGRI_BD", "StringConexaoSGRI_BD")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StringConexaoSGRI_BD object.
        /// </summary>
        public StringConexaoSGRI_BD(string connectionString) : base(connectionString, "StringConexaoSGRI_BD")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StringConexaoSGRI_BD object.
        /// </summary>
        public StringConexaoSGRI_BD(EntityConnection connection) : base(connection, "StringConexaoSGRI_BD")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EQUIPAMENTOS> EQUIPAMENTOS
        {
            get
            {
                if ((_EQUIPAMENTOS == null))
                {
                    _EQUIPAMENTOS = base.CreateObjectSet<EQUIPAMENTOS>("EQUIPAMENTOS");
                }
                return _EQUIPAMENTOS;
            }
        }
        private ObjectSet<EQUIPAMENTOS> _EQUIPAMENTOS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SALAS> SALAS
        {
            get
            {
                if ((_SALAS == null))
                {
                    _SALAS = base.CreateObjectSet<SALAS>("SALAS");
                }
                return _SALAS;
            }
        }
        private ObjectSet<SALAS> _SALAS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FUNCIONARIOS> FUNCIONARIOS
        {
            get
            {
                if ((_FUNCIONARIOS == null))
                {
                    _FUNCIONARIOS = base.CreateObjectSet<FUNCIONARIOS>("FUNCIONARIOS");
                }
                return _FUNCIONARIOS;
            }
        }
        private ObjectSet<FUNCIONARIOS> _FUNCIONARIOS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TURMA_HORARIO> TURMA_HORARIO
        {
            get
            {
                if ((_TURMA_HORARIO == null))
                {
                    _TURMA_HORARIO = base.CreateObjectSet<TURMA_HORARIO>("TURMA_HORARIO");
                }
                return _TURMA_HORARIO;
            }
        }
        private ObjectSet<TURMA_HORARIO> _TURMA_HORARIO;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RESERVA_AULAS> RESERVA_AULAS
        {
            get
            {
                if ((_RESERVA_AULAS == null))
                {
                    _RESERVA_AULAS = base.CreateObjectSet<RESERVA_AULAS>("RESERVA_AULAS");
                }
                return _RESERVA_AULAS;
            }
        }
        private ObjectSet<RESERVA_AULAS> _RESERVA_AULAS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RESERVA_EVENTOS> RESERVA_EVENTOS
        {
            get
            {
                if ((_RESERVA_EVENTOS == null))
                {
                    _RESERVA_EVENTOS = base.CreateObjectSet<RESERVA_EVENTOS>("RESERVA_EVENTOS");
                }
                return _RESERVA_EVENTOS;
            }
        }
        private ObjectSet<RESERVA_EVENTOS> _RESERVA_EVENTOS;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EQUIPAMENTOS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEQUIPAMENTOS(EQUIPAMENTOS eQUIPAMENTOS)
        {
            base.AddObject("EQUIPAMENTOS", eQUIPAMENTOS);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SALAS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSALAS(SALAS sALAS)
        {
            base.AddObject("SALAS", sALAS);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FUNCIONARIOS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFUNCIONARIOS(FUNCIONARIOS fUNCIONARIOS)
        {
            base.AddObject("FUNCIONARIOS", fUNCIONARIOS);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TURMA_HORARIO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTURMA_HORARIO(TURMA_HORARIO tURMA_HORARIO)
        {
            base.AddObject("TURMA_HORARIO", tURMA_HORARIO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RESERVA_AULAS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRESERVA_AULAS(RESERVA_AULAS rESERVA_AULAS)
        {
            base.AddObject("RESERVA_AULAS", rESERVA_AULAS);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RESERVA_EVENTOS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRESERVA_EVENTOS(RESERVA_EVENTOS rESERVA_EVENTOS)
        {
            base.AddObject("RESERVA_EVENTOS", rESERVA_EVENTOS);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SGRI_BDModel", Name="EQUIPAMENTOS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EQUIPAMENTOS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EQUIPAMENTOS object.
        /// </summary>
        /// <param name="iDEquipamento">Initial value of the IDEquipamento property.</param>
        public static EQUIPAMENTOS CreateEQUIPAMENTOS(global::System.Int32 iDEquipamento)
        {
            EQUIPAMENTOS eQUIPAMENTOS = new EQUIPAMENTOS();
            eQUIPAMENTOS.IDEquipamento = iDEquipamento;
            return eQUIPAMENTOS;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDEquipamento
        {
            get
            {
                return _IDEquipamento;
            }
            set
            {
                if (_IDEquipamento != value)
                {
                    OnIDEquipamentoChanging(value);
                    ReportPropertyChanging("IDEquipamento");
                    _IDEquipamento = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDEquipamento");
                    OnIDEquipamentoChanged();
                }
            }
        }
        private global::System.Int32 _IDEquipamento;
        partial void OnIDEquipamentoChanging(global::System.Int32 value);
        partial void OnIDEquipamentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Codigo_Patrimonio
        {
            get
            {
                return _Codigo_Patrimonio;
            }
            set
            {
                OnCodigo_PatrimonioChanging(value);
                ReportPropertyChanging("Codigo_Patrimonio");
                _Codigo_Patrimonio = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Codigo_Patrimonio");
                OnCodigo_PatrimonioChanged();
            }
        }
        private global::System.String _Codigo_Patrimonio;
        partial void OnCodigo_PatrimonioChanging(global::System.String value);
        partial void OnCodigo_PatrimonioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tipo_Equipamento
        {
            get
            {
                return _Tipo_Equipamento;
            }
            set
            {
                OnTipo_EquipamentoChanging(value);
                ReportPropertyChanging("Tipo_Equipamento");
                _Tipo_Equipamento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tipo_Equipamento");
                OnTipo_EquipamentoChanged();
            }
        }
        private global::System.String _Tipo_Equipamento;
        partial void OnTipo_EquipamentoChanging(global::System.String value);
        partial void OnTipo_EquipamentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descricao_Equipamento
        {
            get
            {
                return _Descricao_Equipamento;
            }
            set
            {
                OnDescricao_EquipamentoChanging(value);
                ReportPropertyChanging("Descricao_Equipamento");
                _Descricao_Equipamento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descricao_Equipamento");
                OnDescricao_EquipamentoChanged();
            }
        }
        private global::System.String _Descricao_Equipamento;
        partial void OnDescricao_EquipamentoChanging(global::System.String value);
        partial void OnDescricao_EquipamentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status_Equipamento
        {
            get
            {
                return _Status_Equipamento;
            }
            set
            {
                OnStatus_EquipamentoChanging(value);
                ReportPropertyChanging("Status_Equipamento");
                _Status_Equipamento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status_Equipamento");
                OnStatus_EquipamentoChanged();
            }
        }
        private global::System.String _Status_Equipamento;
        partial void OnStatus_EquipamentoChanging(global::System.String value);
        partial void OnStatus_EquipamentoChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SGRI_BDModel", Name="FUNCIONARIOS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FUNCIONARIOS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FUNCIONARIOS object.
        /// </summary>
        /// <param name="iDFuncionario">Initial value of the IDFuncionario property.</param>
        public static FUNCIONARIOS CreateFUNCIONARIOS(global::System.Int32 iDFuncionario)
        {
            FUNCIONARIOS fUNCIONARIOS = new FUNCIONARIOS();
            fUNCIONARIOS.IDFuncionario = iDFuncionario;
            return fUNCIONARIOS;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDFuncionario
        {
            get
            {
                return _IDFuncionario;
            }
            set
            {
                if (_IDFuncionario != value)
                {
                    OnIDFuncionarioChanging(value);
                    ReportPropertyChanging("IDFuncionario");
                    _IDFuncionario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDFuncionario");
                    OnIDFuncionarioChanged();
                }
            }
        }
        private global::System.Int32 _IDFuncionario;
        partial void OnIDFuncionarioChanging(global::System.Int32 value);
        partial void OnIDFuncionarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Matricula_Funcionario
        {
            get
            {
                return _Matricula_Funcionario;
            }
            set
            {
                OnMatricula_FuncionarioChanging(value);
                ReportPropertyChanging("Matricula_Funcionario");
                _Matricula_Funcionario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Matricula_Funcionario");
                OnMatricula_FuncionarioChanged();
            }
        }
        private global::System.String _Matricula_Funcionario;
        partial void OnMatricula_FuncionarioChanging(global::System.String value);
        partial void OnMatricula_FuncionarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nome_Funcionario
        {
            get
            {
                return _Nome_Funcionario;
            }
            set
            {
                OnNome_FuncionarioChanging(value);
                ReportPropertyChanging("Nome_Funcionario");
                _Nome_Funcionario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nome_Funcionario");
                OnNome_FuncionarioChanged();
            }
        }
        private global::System.String _Nome_Funcionario;
        partial void OnNome_FuncionarioChanging(global::System.String value);
        partial void OnNome_FuncionarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tipo_Funcionario
        {
            get
            {
                return _Tipo_Funcionario;
            }
            set
            {
                OnTipo_FuncionarioChanging(value);
                ReportPropertyChanging("Tipo_Funcionario");
                _Tipo_Funcionario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tipo_Funcionario");
                OnTipo_FuncionarioChanged();
            }
        }
        private global::System.String _Tipo_Funcionario;
        partial void OnTipo_FuncionarioChanging(global::System.String value);
        partial void OnTipo_FuncionarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cargo_Funcionario
        {
            get
            {
                return _Cargo_Funcionario;
            }
            set
            {
                OnCargo_FuncionarioChanging(value);
                ReportPropertyChanging("Cargo_Funcionario");
                _Cargo_Funcionario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Cargo_Funcionario");
                OnCargo_FuncionarioChanged();
            }
        }
        private global::System.String _Cargo_Funcionario;
        partial void OnCargo_FuncionarioChanging(global::System.String value);
        partial void OnCargo_FuncionarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Login_Funcionario
        {
            get
            {
                return _Login_Funcionario;
            }
            set
            {
                OnLogin_FuncionarioChanging(value);
                ReportPropertyChanging("Login_Funcionario");
                _Login_Funcionario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Login_Funcionario");
                OnLogin_FuncionarioChanged();
            }
        }
        private global::System.String _Login_Funcionario;
        partial void OnLogin_FuncionarioChanging(global::System.String value);
        partial void OnLogin_FuncionarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Senha_Funcionario
        {
            get
            {
                return _Senha_Funcionario;
            }
            set
            {
                OnSenha_FuncionarioChanging(value);
                ReportPropertyChanging("Senha_Funcionario");
                _Senha_Funcionario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Senha_Funcionario");
                OnSenha_FuncionarioChanged();
            }
        }
        private global::System.String _Senha_Funcionario;
        partial void OnSenha_FuncionarioChanging(global::System.String value);
        partial void OnSenha_FuncionarioChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SGRI_BDModel", Name="RESERVA_AULAS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RESERVA_AULAS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RESERVA_AULAS object.
        /// </summary>
        /// <param name="iDReserva_Aula">Initial value of the IDReserva_Aula property.</param>
        public static RESERVA_AULAS CreateRESERVA_AULAS(global::System.Int32 iDReserva_Aula)
        {
            RESERVA_AULAS rESERVA_AULAS = new RESERVA_AULAS();
            rESERVA_AULAS.IDReserva_Aula = iDReserva_Aula;
            return rESERVA_AULAS;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDReserva_Aula
        {
            get
            {
                return _IDReserva_Aula;
            }
            set
            {
                if (_IDReserva_Aula != value)
                {
                    OnIDReserva_AulaChanging(value);
                    ReportPropertyChanging("IDReserva_Aula");
                    _IDReserva_Aula = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDReserva_Aula");
                    OnIDReserva_AulaChanged();
                }
            }
        }
        private global::System.Int32 _IDReserva_Aula;
        partial void OnIDReserva_AulaChanging(global::System.Int32 value);
        partial void OnIDReserva_AulaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Data_Reserva
        {
            get
            {
                return _Data_Reserva;
            }
            set
            {
                OnData_ReservaChanging(value);
                ReportPropertyChanging("Data_Reserva");
                _Data_Reserva = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Data_Reserva");
                OnData_ReservaChanged();
            }
        }
        private global::System.String _Data_Reserva;
        partial void OnData_ReservaChanging(global::System.String value);
        partial void OnData_ReservaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Professor_Aula
        {
            get
            {
                return _Professor_Aula;
            }
            set
            {
                OnProfessor_AulaChanging(value);
                ReportPropertyChanging("Professor_Aula");
                _Professor_Aula = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Professor_Aula");
                OnProfessor_AulaChanged();
            }
        }
        private global::System.String _Professor_Aula;
        partial void OnProfessor_AulaChanging(global::System.String value);
        partial void OnProfessor_AulaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Disciplina_Aula
        {
            get
            {
                return _Disciplina_Aula;
            }
            set
            {
                OnDisciplina_AulaChanging(value);
                ReportPropertyChanging("Disciplina_Aula");
                _Disciplina_Aula = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Disciplina_Aula");
                OnDisciplina_AulaChanged();
            }
        }
        private global::System.String _Disciplina_Aula;
        partial void OnDisciplina_AulaChanging(global::System.String value);
        partial void OnDisciplina_AulaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Horario_Aula
        {
            get
            {
                return _Horario_Aula;
            }
            set
            {
                OnHorario_AulaChanging(value);
                ReportPropertyChanging("Horario_Aula");
                _Horario_Aula = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Horario_Aula");
                OnHorario_AulaChanged();
            }
        }
        private global::System.String _Horario_Aula;
        partial void OnHorario_AulaChanging(global::System.String value);
        partial void OnHorario_AulaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Dia_Aula
        {
            get
            {
                return _Dia_Aula;
            }
            set
            {
                OnDia_AulaChanging(value);
                ReportPropertyChanging("Dia_Aula");
                _Dia_Aula = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Dia_Aula");
                OnDia_AulaChanged();
            }
        }
        private global::System.String _Dia_Aula;
        partial void OnDia_AulaChanging(global::System.String value);
        partial void OnDia_AulaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Equipamento_Aula
        {
            get
            {
                return _Equipamento_Aula;
            }
            set
            {
                OnEquipamento_AulaChanging(value);
                ReportPropertyChanging("Equipamento_Aula");
                _Equipamento_Aula = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Equipamento_Aula");
                OnEquipamento_AulaChanged();
            }
        }
        private global::System.String _Equipamento_Aula;
        partial void OnEquipamento_AulaChanging(global::System.String value);
        partial void OnEquipamento_AulaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sala_Aula
        {
            get
            {
                return _Sala_Aula;
            }
            set
            {
                OnSala_AulaChanging(value);
                ReportPropertyChanging("Sala_Aula");
                _Sala_Aula = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sala_Aula");
                OnSala_AulaChanged();
            }
        }
        private global::System.String _Sala_Aula;
        partial void OnSala_AulaChanging(global::System.String value);
        partial void OnSala_AulaChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SGRI_BDModel", Name="RESERVA_EVENTOS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RESERVA_EVENTOS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RESERVA_EVENTOS object.
        /// </summary>
        /// <param name="iDReserva_Evento">Initial value of the IDReserva_Evento property.</param>
        public static RESERVA_EVENTOS CreateRESERVA_EVENTOS(global::System.Int32 iDReserva_Evento)
        {
            RESERVA_EVENTOS rESERVA_EVENTOS = new RESERVA_EVENTOS();
            rESERVA_EVENTOS.IDReserva_Evento = iDReserva_Evento;
            return rESERVA_EVENTOS;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDReserva_Evento
        {
            get
            {
                return _IDReserva_Evento;
            }
            set
            {
                if (_IDReserva_Evento != value)
                {
                    OnIDReserva_EventoChanging(value);
                    ReportPropertyChanging("IDReserva_Evento");
                    _IDReserva_Evento = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDReserva_Evento");
                    OnIDReserva_EventoChanged();
                }
            }
        }
        private global::System.Int32 _IDReserva_Evento;
        partial void OnIDReserva_EventoChanging(global::System.Int32 value);
        partial void OnIDReserva_EventoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nome_Evento
        {
            get
            {
                return _Nome_Evento;
            }
            set
            {
                OnNome_EventoChanging(value);
                ReportPropertyChanging("Nome_Evento");
                _Nome_Evento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nome_Evento");
                OnNome_EventoChanged();
            }
        }
        private global::System.String _Nome_Evento;
        partial void OnNome_EventoChanging(global::System.String value);
        partial void OnNome_EventoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Data_Evento
        {
            get
            {
                return _Data_Evento;
            }
            set
            {
                OnData_EventoChanging(value);
                ReportPropertyChanging("Data_Evento");
                _Data_Evento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Data_Evento");
                OnData_EventoChanged();
            }
        }
        private global::System.String _Data_Evento;
        partial void OnData_EventoChanging(global::System.String value);
        partial void OnData_EventoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Prorfessores_Evento
        {
            get
            {
                return _Prorfessores_Evento;
            }
            set
            {
                OnProrfessores_EventoChanging(value);
                ReportPropertyChanging("Prorfessores_Evento");
                _Prorfessores_Evento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Prorfessores_Evento");
                OnProrfessores_EventoChanged();
            }
        }
        private global::System.String _Prorfessores_Evento;
        partial void OnProrfessores_EventoChanging(global::System.String value);
        partial void OnProrfessores_EventoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sala_Evento
        {
            get
            {
                return _Sala_Evento;
            }
            set
            {
                OnSala_EventoChanging(value);
                ReportPropertyChanging("Sala_Evento");
                _Sala_Evento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sala_Evento");
                OnSala_EventoChanged();
            }
        }
        private global::System.String _Sala_Evento;
        partial void OnSala_EventoChanging(global::System.String value);
        partial void OnSala_EventoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Equipamentos_Evento
        {
            get
            {
                return _Equipamentos_Evento;
            }
            set
            {
                OnEquipamentos_EventoChanging(value);
                ReportPropertyChanging("Equipamentos_Evento");
                _Equipamentos_Evento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Equipamentos_Evento");
                OnEquipamentos_EventoChanged();
            }
        }
        private global::System.String _Equipamentos_Evento;
        partial void OnEquipamentos_EventoChanging(global::System.String value);
        partial void OnEquipamentos_EventoChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SGRI_BDModel", Name="SALAS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SALAS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SALAS object.
        /// </summary>
        /// <param name="iDSala">Initial value of the IDSala property.</param>
        public static SALAS CreateSALAS(global::System.Int32 iDSala)
        {
            SALAS sALAS = new SALAS();
            sALAS.IDSala = iDSala;
            return sALAS;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDSala
        {
            get
            {
                return _IDSala;
            }
            set
            {
                if (_IDSala != value)
                {
                    OnIDSalaChanging(value);
                    ReportPropertyChanging("IDSala");
                    _IDSala = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDSala");
                    OnIDSalaChanged();
                }
            }
        }
        private global::System.Int32 _IDSala;
        partial void OnIDSalaChanging(global::System.Int32 value);
        partial void OnIDSalaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descricao_Sala
        {
            get
            {
                return _Descricao_Sala;
            }
            set
            {
                OnDescricao_SalaChanging(value);
                ReportPropertyChanging("Descricao_Sala");
                _Descricao_Sala = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descricao_Sala");
                OnDescricao_SalaChanged();
            }
        }
        private global::System.String _Descricao_Sala;
        partial void OnDescricao_SalaChanging(global::System.String value);
        partial void OnDescricao_SalaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Localizacao_Sala
        {
            get
            {
                return _Localizacao_Sala;
            }
            set
            {
                OnLocalizacao_SalaChanging(value);
                ReportPropertyChanging("Localizacao_Sala");
                _Localizacao_Sala = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Localizacao_Sala");
                OnLocalizacao_SalaChanged();
            }
        }
        private global::System.String _Localizacao_Sala;
        partial void OnLocalizacao_SalaChanging(global::System.String value);
        partial void OnLocalizacao_SalaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Capacidade_Sala
        {
            get
            {
                return _Capacidade_Sala;
            }
            set
            {
                OnCapacidade_SalaChanging(value);
                ReportPropertyChanging("Capacidade_Sala");
                _Capacidade_Sala = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Capacidade_Sala");
                OnCapacidade_SalaChanged();
            }
        }
        private Nullable<global::System.Int32> _Capacidade_Sala;
        partial void OnCapacidade_SalaChanging(Nullable<global::System.Int32> value);
        partial void OnCapacidade_SalaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tipo_Sala
        {
            get
            {
                return _Tipo_Sala;
            }
            set
            {
                OnTipo_SalaChanging(value);
                ReportPropertyChanging("Tipo_Sala");
                _Tipo_Sala = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tipo_Sala");
                OnTipo_SalaChanged();
            }
        }
        private global::System.String _Tipo_Sala;
        partial void OnTipo_SalaChanging(global::System.String value);
        partial void OnTipo_SalaChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SGRI_BDModel", Name="TURMA_HORARIO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TURMA_HORARIO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TURMA_HORARIO object.
        /// </summary>
        /// <param name="iDTurma">Initial value of the IDTurma property.</param>
        public static TURMA_HORARIO CreateTURMA_HORARIO(global::System.Int32 iDTurma)
        {
            TURMA_HORARIO tURMA_HORARIO = new TURMA_HORARIO();
            tURMA_HORARIO.IDTurma = iDTurma;
            return tURMA_HORARIO;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDTurma
        {
            get
            {
                return _IDTurma;
            }
            set
            {
                if (_IDTurma != value)
                {
                    OnIDTurmaChanging(value);
                    ReportPropertyChanging("IDTurma");
                    _IDTurma = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDTurma");
                    OnIDTurmaChanged();
                }
            }
        }
        private global::System.Int32 _IDTurma;
        partial void OnIDTurmaChanging(global::System.Int32 value);
        partial void OnIDTurmaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Turma
        {
            get
            {
                return _Turma;
            }
            set
            {
                OnTurmaChanging(value);
                ReportPropertyChanging("Turma");
                _Turma = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Turma");
                OnTurmaChanged();
            }
        }
        private global::System.String _Turma;
        partial void OnTurmaChanging(global::System.String value);
        partial void OnTurmaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Horario
        {
            get
            {
                return _Horario;
            }
            set
            {
                OnHorarioChanging(value);
                ReportPropertyChanging("Horario");
                _Horario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Horario");
                OnHorarioChanged();
            }
        }
        private global::System.String _Horario;
        partial void OnHorarioChanging(global::System.String value);
        partial void OnHorarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sala
        {
            get
            {
                return _Sala;
            }
            set
            {
                OnSalaChanging(value);
                ReportPropertyChanging("Sala");
                _Sala = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sala");
                OnSalaChanged();
            }
        }
        private global::System.String _Sala;
        partial void OnSalaChanging(global::System.String value);
        partial void OnSalaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Professor_Turma
        {
            get
            {
                return _Professor_Turma;
            }
            set
            {
                OnProfessor_TurmaChanging(value);
                ReportPropertyChanging("Professor_Turma");
                _Professor_Turma = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Professor_Turma");
                OnProfessor_TurmaChanged();
            }
        }
        private global::System.String _Professor_Turma;
        partial void OnProfessor_TurmaChanging(global::System.String value);
        partial void OnProfessor_TurmaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Andar_Sala
        {
            get
            {
                return _Andar_Sala;
            }
            set
            {
                OnAndar_SalaChanging(value);
                ReportPropertyChanging("Andar_Sala");
                _Andar_Sala = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Andar_Sala");
                OnAndar_SalaChanged();
            }
        }
        private global::System.String _Andar_Sala;
        partial void OnAndar_SalaChanging(global::System.String value);
        partial void OnAndar_SalaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Predio_Sala
        {
            get
            {
                return _Predio_Sala;
            }
            set
            {
                OnPredio_SalaChanging(value);
                ReportPropertyChanging("Predio_Sala");
                _Predio_Sala = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Predio_Sala");
                OnPredio_SalaChanged();
            }
        }
        private global::System.String _Predio_Sala;
        partial void OnPredio_SalaChanging(global::System.String value);
        partial void OnPredio_SalaChanged();

        #endregion
    
    }

    #endregion
    
}
