//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace SGRIMvc.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class StringConexaoSGRI_BD : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new StringConexaoSGRI_BD object using the connection string found in the 'StringConexaoSGRI_BD' section of the application configuration file.
        /// </summary>
        public StringConexaoSGRI_BD() : base("name=StringConexaoSGRI_BD", "StringConexaoSGRI_BD")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StringConexaoSGRI_BD object.
        /// </summary>
        public StringConexaoSGRI_BD(string connectionString) : base(connectionString, "StringConexaoSGRI_BD")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StringConexaoSGRI_BD object.
        /// </summary>
        public StringConexaoSGRI_BD(EntityConnection connection) : base(connection, "StringConexaoSGRI_BD")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EQUIPAMENTOS> EQUIPAMENTOS
        {
            get
            {
                if ((_EQUIPAMENTOS == null))
                {
                    _EQUIPAMENTOS = base.CreateObjectSet<EQUIPAMENTOS>("EQUIPAMENTOS");
                }
                return _EQUIPAMENTOS;
            }
        }
        private ObjectSet<EQUIPAMENTOS> _EQUIPAMENTOS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SALAS> SALAS
        {
            get
            {
                if ((_SALAS == null))
                {
                    _SALAS = base.CreateObjectSet<SALAS>("SALAS");
                }
                return _SALAS;
            }
        }
        private ObjectSet<SALAS> _SALAS;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EQUIPAMENTOS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEQUIPAMENTOS(EQUIPAMENTOS eQUIPAMENTOS)
        {
            base.AddObject("EQUIPAMENTOS", eQUIPAMENTOS);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SALAS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSALAS(SALAS sALAS)
        {
            base.AddObject("SALAS", sALAS);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SGRI_BDModel", Name="EQUIPAMENTOS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EQUIPAMENTOS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EQUIPAMENTOS object.
        /// </summary>
        /// <param name="iDEquipamento">Initial value of the IDEquipamento property.</param>
        public static EQUIPAMENTOS CreateEQUIPAMENTOS(global::System.Int32 iDEquipamento)
        {
            EQUIPAMENTOS eQUIPAMENTOS = new EQUIPAMENTOS();
            eQUIPAMENTOS.IDEquipamento = iDEquipamento;
            return eQUIPAMENTOS;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDEquipamento
        {
            get
            {
                return _IDEquipamento;
            }
            set
            {
                if (_IDEquipamento != value)
                {
                    OnIDEquipamentoChanging(value);
                    ReportPropertyChanging("IDEquipamento");
                    _IDEquipamento = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDEquipamento");
                    OnIDEquipamentoChanged();
                }
            }
        }
        private global::System.Int32 _IDEquipamento;
        partial void OnIDEquipamentoChanging(global::System.Int32 value);
        partial void OnIDEquipamentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Codigo_Patrimonio
        {
            get
            {
                return _Codigo_Patrimonio;
            }
            set
            {
                OnCodigo_PatrimonioChanging(value);
                ReportPropertyChanging("Codigo_Patrimonio");
                _Codigo_Patrimonio = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Codigo_Patrimonio");
                OnCodigo_PatrimonioChanged();
            }
        }
        private global::System.String _Codigo_Patrimonio;
        partial void OnCodigo_PatrimonioChanging(global::System.String value);
        partial void OnCodigo_PatrimonioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tipo_Equipamento
        {
            get
            {
                return _Tipo_Equipamento;
            }
            set
            {
                OnTipo_EquipamentoChanging(value);
                ReportPropertyChanging("Tipo_Equipamento");
                _Tipo_Equipamento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tipo_Equipamento");
                OnTipo_EquipamentoChanged();
            }
        }
        private global::System.String _Tipo_Equipamento;
        partial void OnTipo_EquipamentoChanging(global::System.String value);
        partial void OnTipo_EquipamentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descricao_Equipamento
        {
            get
            {
                return _Descricao_Equipamento;
            }
            set
            {
                OnDescricao_EquipamentoChanging(value);
                ReportPropertyChanging("Descricao_Equipamento");
                _Descricao_Equipamento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descricao_Equipamento");
                OnDescricao_EquipamentoChanged();
            }
        }
        private global::System.String _Descricao_Equipamento;
        partial void OnDescricao_EquipamentoChanging(global::System.String value);
        partial void OnDescricao_EquipamentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status_Equipamento
        {
            get
            {
                return _Status_Equipamento;
            }
            set
            {
                OnStatus_EquipamentoChanging(value);
                ReportPropertyChanging("Status_Equipamento");
                _Status_Equipamento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status_Equipamento");
                OnStatus_EquipamentoChanged();
            }
        }
        private global::System.String _Status_Equipamento;
        partial void OnStatus_EquipamentoChanging(global::System.String value);
        partial void OnStatus_EquipamentoChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SGRI_BDModel", Name="SALAS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SALAS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SALAS object.
        /// </summary>
        /// <param name="iDSala">Initial value of the IDSala property.</param>
        public static SALAS CreateSALAS(global::System.Int32 iDSala)
        {
            SALAS sALAS = new SALAS();
            sALAS.IDSala = iDSala;
            return sALAS;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDSala
        {
            get
            {
                return _IDSala;
            }
            set
            {
                if (_IDSala != value)
                {
                    OnIDSalaChanging(value);
                    ReportPropertyChanging("IDSala");
                    _IDSala = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDSala");
                    OnIDSalaChanged();
                }
            }
        }
        private global::System.Int32 _IDSala;
        partial void OnIDSalaChanging(global::System.Int32 value);
        partial void OnIDSalaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descricao_Sala
        {
            get
            {
                return _Descricao_Sala;
            }
            set
            {
                OnDescricao_SalaChanging(value);
                ReportPropertyChanging("Descricao_Sala");
                _Descricao_Sala = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descricao_Sala");
                OnDescricao_SalaChanged();
            }
        }
        private global::System.String _Descricao_Sala;
        partial void OnDescricao_SalaChanging(global::System.String value);
        partial void OnDescricao_SalaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Localizacao_Sala
        {
            get
            {
                return _Localizacao_Sala;
            }
            set
            {
                OnLocalizacao_SalaChanging(value);
                ReportPropertyChanging("Localizacao_Sala");
                _Localizacao_Sala = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Localizacao_Sala");
                OnLocalizacao_SalaChanged();
            }
        }
        private global::System.String _Localizacao_Sala;
        partial void OnLocalizacao_SalaChanging(global::System.String value);
        partial void OnLocalizacao_SalaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Capacidade_Sala
        {
            get
            {
                return _Capacidade_Sala;
            }
            set
            {
                OnCapacidade_SalaChanging(value);
                ReportPropertyChanging("Capacidade_Sala");
                _Capacidade_Sala = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Capacidade_Sala");
                OnCapacidade_SalaChanged();
            }
        }
        private Nullable<global::System.Int32> _Capacidade_Sala;
        partial void OnCapacidade_SalaChanging(Nullable<global::System.Int32> value);
        partial void OnCapacidade_SalaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tipo_Sala
        {
            get
            {
                return _Tipo_Sala;
            }
            set
            {
                OnTipo_SalaChanging(value);
                ReportPropertyChanging("Tipo_Sala");
                _Tipo_Sala = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tipo_Sala");
                OnTipo_SalaChanged();
            }
        }
        private global::System.String _Tipo_Sala;
        partial void OnTipo_SalaChanging(global::System.String value);
        partial void OnTipo_SalaChanged();

        #endregion
    
    }

    #endregion
    
}
